services:
  web:
    build:
      context: src/web
      dockerfile: development.Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8080:8080" # Used for test startup wait
    volumes:
      - ./src/web:/web # Used for live reloading
